// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { ThemeService } from './services/theme/theme.service';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  isDark$: BehaviorSubject<boolean> = this.themeService.isDark$;

  constructor(
    private themeService: ThemeService,
  ) {}

  changeTheme(): void {
    this.isDark$.next(!this.isDark$.getValue());
  }
}

<div class="wrapper">
  <header>
    <div class="title" [ngClass]="{'dark': isDark$ | async}" routerLink="/">Delat<span>'</span></div>
    <div class="buttons">
      <img [src]="(isDark$ | async) ? 'assets/svg/delete-dark-24px.svg' : 'assets/svg/delete-24px.svg'" routerLink="/trashcan">
      <img [src]="(isDark$ | async) ? 'assets/svg/wb_sunny-dark-24px.svg' : 'assets/svg/wb_sunny-24px.svg'" class="dark" (click)="changeTheme()">
    </div>
  </header>
  <main>
    <router-outlet></router-outlet>
  </main>
</div>

// react/src/App.js
import React from 'react'
import { BrowserRouter as Router, Route, Switch } from 'react-router-dom'
import './App.scss'
import { NewCard } from './features/new-card/NewCard'
import { Home } from './features/home/Home'
import { ReactComponent as DeleteIcon } from './assets/svg/delete-24px.svg'
import { ReactComponent as WBSunnyIcon } from './assets/svg/wb_sunny-24px.svg'

function App () {
  return (
    <div className="wrapper">
      <header>
        <div className="title">Delat<span>'</span>
        </div>
        <div className="buttons">
          <DeleteIcon/>
          <WBSunnyIcon/>
        </div>
      </header>
      <main>
        <Router>
          <Switch>
            <Route path="/new">
              <NewCard />
            </Route>
            <Route path="/">
              <Home />
            </Route>
          </Switch>
        </Router>
      </main>
    </div>

  )
}

export default App
