// react/src/App.tsx
import React, { useContext, useEffect, useState } from 'react'
import {
  BrowserRouter as Router,
  Route,
  Switch,
  useHistory,
} from 'react-router-dom'
import './App.scss'
import { NewCard } from './features/new-card/NewCard'
import { Home } from './features/home/Home'
import { ReactComponent as DeleteIcon } from './assets/svg/delete-24px.svg'
import { ReactComponent as WBSunnyIcon } from './assets/svg/wb_sunny-24px.svg'
import Themes from './models/themes'
import { Trashcan } from './features/trashcan/Trashcan'

export const ThemeContext = React.createContext(Themes.LIGHT)

function App () {
  const [theme, setTheme] = useState(useContext(ThemeContext))
  const toggleTheme = () => {
    theme === Themes.DARK
      ? setTheme(Themes.LIGHT)
      : setTheme(Themes.DARK)
  }
  const history = useHistory()

  const navigateToTrashcan = () => history.push('/trashcan')

  useEffect(() => {
    const BODY_DARK_CLASS = 'dark'
    theme === Themes.DARK
      ? document.body.classList.add(BODY_DARK_CLASS)
      : document.body.classList.remove(BODY_DARK_CLASS)
  }, [theme])

  return (
    <ThemeContext.Provider value={theme}>
        <div className="wrapper">
          <header>
            <div className="title">Delat<span>'</span>
            </div>
            <div className="buttons">
              <DeleteIcon onClick={navigateToTrashcan}/>
              <WBSunnyIcon onClick={toggleTheme}/>
            </div>
          </header>
          <main>
            <Switch>
              <Route path="/new">
                <NewCard/>
              </Route>
              <Route path="/trashcan">
                <Trashcan/>
              </Route>
              <Route path="/">
                <Home/>
              </Route>
            </Switch>
          </main>
        </div>
    </ThemeContext.Provider>
  )
}

export default App

// angular/src/app/app.component.ts
import { Component, ElementRef } from '@angular/core';
import { ThemeService } from './services/theme/theme.service';
import { BehaviorSubject } from 'rxjs';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  title = 'todo-app';
  isDark$: BehaviorSubject<boolean> = this.themeService.isDark$;

  constructor(
    private themeService: ThemeService,
    private elementRef: ElementRef,
  ) {}

  changeTheme(): void {
    const isDark = this.isDark$.getValue();
    isDark ? this.isDark$.next(false) : this.isDark$.next(true);

    const BODY_DARK_CLASS = 'dark';
    this.elementRef.nativeElement.ownerDocument.body.classList.toggle(BODY_DARK_CLASS);
  }
}

<div class="wrapper">
  <header>
    <div class="title" [ngClass]="{'dark': isDark$ | async}" routerLink="/">Delat<span>'</span></div>
    <div class="buttons">
      <img [src]="(isDark$ | async) ? 'assets/svg/delete-dark-24px.svg' : 'assets/svg/delete-24px.svg'" routerLink="/trashcan">
      <img [src]="(isDark$ | async) ? 'assets/svg/wb_sunny-dark-24px.svg' : 'assets/svg/wb_sunny-24px.svg'" class="dark" (click)="changeTheme()">
    </div>
  </header>
  <main>
    <router-outlet></router-outlet>
  </main>
</div>
