// react/src/components/trashcan/Trashcan.tsx
import React, { useEffect, useState } from 'react'
import './Trashcan.scss'
import { TaskItem } from '../../ui/task-item/TaskItem'
import { SectionTitle } from '../../ui/section-title/SectionTitle'
import { ITask } from '../../models/ITask'
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service'

export const Trashcan = () => {
  const [tasks, setTasks] = useState<ITask[]>([])

  const tasksStorage = new TasksStorageService();

  const onClearAll = () => {}
  const onRestoreAll = () => {}

  useEffect(() => {
    setTasks(tasksStorage.getTasks().filter(task => task.isArchived));
  }, [])

  return (
    <section>
      <header>
        <SectionTitle clickable={false} title="Archived"/>
        <div className="buttons">
          <div className="button" onClick={onClearAll}>Clear all</div>
          <div className="button" onClick={onRestoreAll}>Restore all</div>
        </div>
      </header>
      { tasks.length > 0 ? tasks.map((task: ITask) => <TaskItem key={task.id} task={task}/>) : null}
    </section>
  )
}

// angular/src/app/components/trashcan/trashcan.component.ts
import { Component, OnInit } from '@angular/core';
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service';
import { Task } from 'src/app/models/task';

@Component({
  selector: 'app-trashcan',
  templateUrl: './trashcan.component.html',
  styleUrls: ['./trashcan.component.scss']
})
export class TrashcanComponent implements OnInit {
  tasks: Task[];

  constructor(
    private tasksStorage: TasksStorageService
  ) { }

  ngOnInit(): void {
    this.tasks = this.tasksStorage.getTasks().filter(task => task.isArchived);
  }
}

<section @enter>
  <header>
    <app-section-title title="Archived"></app-section-title>
    <div class="buttons">
      <div class="button" (click)="onClearAll()">Clear all</div>
      <div class="button" (click)="onRestoreAll()">Restore all</div>
    </div>
  </header>
  <app-task-item *ngFor="let task of tasks" [task]="task"></app-task-item>
</section>
