// react/src/features/home/Home.tsx
import React, { useContext } from 'react'
import './Home.scss'
import { TaskItem } from '../../ui/task-item/TaskItem'
import { SectionTitle } from '../../ui/section-title/SectionTitle'
import { Colors } from '../../models/colors'
import { useHistory } from 'react-router-dom'
import { ThemeContext } from '../../App'
import Themes from '../../models/themes'

const todayTasks = [
  {
    id: '1',
    title: 'task 1',
    date: new Date('1995-12-17T03:24:00').toDateString(),
    color: Colors.RED,
    isFavorite: false,
    isArchived: false,
  },
]

export const Home: React.FC = () => {
  const history = useHistory()
  const theme = useContext(ThemeContext);

  return (
    <div className="wrapper">
      <input
        type="text"
        placeholder="New..."
        className={`input__new ${theme === Themes.DARK ? 'dark' : null}`}
        onClick={() => history.push('/new')}/>
      <section>
        <SectionTitle title="Today" onClick={() => {}}/>
        {
          todayTasks.map((task, index) =>
            <TaskItem key="index" task={task} onClick={() => {}}/>)
        }
      </section>
      <section>
        <SectionTitle title="Favourites" onClick={() => {}}/>
        {
          todayTasks.map((task, index) =>
            <TaskItem key="index" task={task} onClick={() => {}}/>)
        }
      </section>
      <section>
        <SectionTitle title="Soon" onClick={() => {}}/>
        {
          todayTasks.map((task, index) =>
            <TaskItem key="index" task={task} onClick={() => {}}/>)
        }
      </section>
      <div className="show-more">See more...</div>
    </div>
  )
}

// angular/src/app/components/home/home.component.ts
import { Component, OnInit } from '@angular/core';
import { ThemeService } from '../../services/theme/theme.service';
import { BehaviorSubject } from 'rxjs';
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service';
import { Task } from 'src/app/models/task';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {
  isDark$: BehaviorSubject<boolean> = this.themeService.isDark$;
  tasks: Task[];
  todayTasks: Task[];
  favoriteTasks: Task[];
  soonTasks: Task[];

  constructor(
    private themeService: ThemeService,
    private tasksStorage: TasksStorageService
  ) { }

  ngOnInit(): void {
    this.tasks = this.tasksStorage.getTasks();
    this.todayTasks = this.tasks.filter(task => task.date === new Date().toDateString()
      && task.isFavorite === false
      && task.isArchived === false);
    this.favoriteTasks = this.tasks.filter(task => task.isFavorite === true && task.isArchived === false);
    this.soonTasks = this.tasks.filter(task => task.date !== new Date().toDateString()
      && task.isFavorite === false
      && task.isArchived === false);
  }
}

<div class="wrapper" @enterHome>
  <div
    class="input__new"
    routerLink="new"
    [ngClass]="{'dark': isDark$ | async}">
    New...
  </div>
  <section *ngIf="todayTasks.length > 0">
    <app-section-title
      title="Today"
      [clickable]="!lists.today"
      (click)="lists.today = !lists.today"></app-section-title>
    <ng-container *ngIf="lists.today">
      <app-task-item
        *ngFor="let task of todayTasks"
        [task]="task"
        [routerLink]="'task'"
        [queryParams]="{id: task.id}"></app-task-item>
    </ng-container>
  </section>
  <section *ngIf="favoriteTasks.length > 0">
    <app-section-title
      title="Favourites"
      [clickable]="!lists.favourites"
      (click)="lists.favourites = !lists.favourites"></app-section-title>
    <ng-container *ngIf="lists.favourites">
      <app-task-item
        *ngFor="let task of favoriteTasks"
        [task]="task"
        [routerLink]="'task'"
        [queryParams]="{id: task.id}"></app-task-item>
    </ng-container>
  </section>
  <section *ngIf="soonTasks.length > 0">
    <app-section-title
      title="Soon"
      [clickable]="!lists.soon"
      (click)="lists.soon = !lists.soon"></app-section-title>
    <ng-container *ngIf="lists.soon">
      <app-task-item
        *ngFor="let task of soonTasks"
        [task]="task"
        [routerLink]="'task'"
        [queryParams]="{id: task.id}"></app-task-item>
    </ng-container>
  </section>
  <section *ngIf="pastTasks.length > 0">
    <app-section-title
      title="Past"
      [clickable]="!lists.past"
      (click)="lists.past = !lists.past"></app-section-title>
    <ng-container *ngIf="lists.past">
      <app-task-item
        *ngFor="let task of soonTasks"
        [task]="task"
        [routerLink]="'task'"
        [queryParams]="{id: task.id}"></app-task-item>
    </ng-container>
  </section>
</div>
