// react/src/components/task/Task.tsx
import React, { useEffect } from 'react'
import './Task.scss'
import { TaskCard } from '../../ui/task-card/TaskCard'
import { useHistory, useLocation } from 'react-router-dom'
import { ITask } from '../../models/ITask'
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service'


export const Task = () => {
  const location = useLocation();
  const history = useHistory();
  const tasksStorageService = new TasksStorageService()

  // @ts-ignore
  const task: ITask = location.state.task;

  useEffect(() => {
    console.log(location.pathname);
    console.log(location.state);
    // @ts-ignore
  }, [location]);

  function onAccept(task: ITask): void {
    tasksStorageService.updateTask(task)
    console.log(task);
    history.push('/')
  }

  return (
    <div className="wrapper">
      <TaskCard task={task} accepted={onAccept} closed={() => history.push('/')}/>
    </div>
  )
}

// angular/src/app/components/task/task.component.ts
import { Component, OnInit } from '@angular/core';
import { ActivatedRoute, Router } from '@angular/router';
import { Task } from 'src/app/models/task';
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service';
import { ThemeService } from '../../services/theme/theme.service';

@Component({
  selector: 'app-task',
  templateUrl: './task.component.html',
  styleUrls: ['./task.component.scss']
})
export class TaskComponent implements OnInit {
  task: Task;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private themeService: ThemeService,
    private tasksStorage: TasksStorageService
  ) { }

  onCancel(): void {
    this.router.navigate(['/']);
  }

  onDone(task: Task): void {
    this.tasksStorage.updateTask(task);
    this.router.navigate(['/']);
  }

  ngOnInit(): void {
    this.route.queryParams.subscribe((params) => {
      this.task = this.tasksStorage.getTaskById(params.id);
    });
  }
}

<div class="wrapper">
  <app-task-card
    [task]="task"
    (closed)="onCancel()"
    (accepted)="onDone($event)"></app-task-card>
</div>
