// react/src/ui/more-menu/MoreMenu.tsx
import React, { useContext, useEffect, useRef, useState } from 'react'
import './MoreMenu.scss'
import { ReactComponent as MoreVertIcon } from '../../assets/svg/more_vert-24px.svg'
import { ReactComponent as MoreVertDarkIcon } from '../../assets/svg/more_vert-dark-24px.svg'
import { ReactComponent as FavoriteBorderIcon } from '../../assets/svg/favorite_border-24px.svg'
import { ReactComponent as FavoriteIcon } from '../../assets/svg/favorite-24px.svg'
import { ReactComponent as FavoriteDarkIcon } from '../../assets/svg/favorite-dark-24px.svg'
import { ReactComponent as DeleteIcon } from '../../assets/svg/delete-24px.svg'
import { ReactComponent as DeleteDarkIcon } from '../../assets/svg/delete-dark-24px.svg'
import { ReactComponent as RestoreFromTrashIcon } from '../../assets/svg/restore_from_trash-24px.svg'
import { ReactComponent as RestoreFromTrashDarkIcon } from '../../assets/svg/restore_from_trash-dark-24px.svg'
import Themes from '../../models/themes'
import { ThemeContext } from '../../App'


type MoreMenuProps = {
  isFavorite: boolean,
  isArchived: boolean,
  onFavorite: () => void,
  onRemove: () => void,
  onRestore: () => void
}

export const MoreMenu = ({
  isFavorite,
  isArchived,
  onFavorite,
  onRemove,
  onRestore
}: MoreMenuProps) => {
  const theme = useContext(ThemeContext)

  const containerRef = useRef(null)

  const [isShow, setIsShow] = useState(false)
  const [isFavoriteState, setIsFavoriteState] = useState(false)

  const onMore = (event: any) => {
    event.stopPropagation()
    setIsShow(!isShow)
  }

  const toggleFavorite = (event: any) => {
    event.stopPropagation()
    setIsFavoriteState(!isFavoriteState)
  }

  const handleClickOutside = (event: any) => {
    if (containerRef && containerRef.current &&
      // @ts-ignore
      !containerRef.current.contains(event.target)) {
      setIsShow(false)
    }
  }

  useEffect(() => {
    console.log(isArchived);
    document.addEventListener('click', handleClickOutside, true)
    return () => {
      document.removeEventListener('click', handleClickOutside, true)
    }
  })

  return (
    <>
      {
        isArchived
          ? theme === Themes.LIGHT
            ? <RestoreFromTrashIcon onClick={onRestore}/>
            : <RestoreFromTrashDarkIcon onClick={onRestore}/>
          : theme === Themes.LIGHT
            ? <MoreVertIcon onClick={onMore}/>
            : <MoreVertDarkIcon onClick={onMore}/>
      }
      {
        isShow ? <div ref={containerRef}>
            <div className={`more-menu ${theme === Themes.DARK ? 'dark' : null}`}>
              <div className="more-menu__item" onClick={toggleFavorite}>
                {
                  isFavoriteState
                    ? theme === Themes.LIGHT ? <FavoriteIcon/> : <FavoriteDarkIcon/>
                    : theme === Themes.LIGHT ? <FavoriteBorderIcon/> : <FavoriteDarkIcon/>
                }
                <span>Add to Favourites</span>
              </div>
              <div className="more-menu__item" onClick={onRemove}>
                {
                  theme === Themes.LIGHT
                    ? <DeleteIcon/>
                    : <DeleteDarkIcon/>
                }
                <span>Remove</span>
              </div>
            </div>
          </div> : null
      }
    </>
  )
}

// angular/src/app/ui/more-menu/more-menu.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  EventEmitter,
  HostListener,
  Input,
  Output,
  TemplateRef,
  ViewChild,
  ViewContainerRef,
} from '@angular/core';
import { BehaviorSubject } from 'rxjs';
import { ThemeService } from '../../services/theme/theme.service';

@Component({
  selector: 'app-more-menu',
  templateUrl: './more-menu.component.html',
  styleUrls: ['./more-menu.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class MoreMenuComponent {
  readonly isDark$: BehaviorSubject<boolean> = this.themeService.isDark$;

  @Output() clickFavorite = new EventEmitter();
  @Output() clickRemove = new EventEmitter();
  @Output() clickRestore = new EventEmitter();

  @Input() isFavorite: boolean;
  @Input() isArchived: boolean;

  isShow = false;

  @ViewChild('template', { read: TemplateRef, static: false }) templateRef: TemplateRef<any>;
  @ViewChild('container', { read: ViewContainerRef, static: true }) viewContainerRef: ViewContainerRef;

  @HostListener('document:click', ['$event', '$event.target'])
  public onClick(event: MouseEvent, targetElement: HTMLElement): void {
    if (!targetElement) {
      return;
    }

    const clickedInside = this.elementRef.nativeElement.contains(targetElement);
    if (!clickedInside) {
      this.hideMenu();
    }
  }

  constructor(
    private elementRef: ElementRef,
    private themeService: ThemeService
  ) { }

  showMenu(): void {
    this.viewContainerRef.createEmbeddedView(this.templateRef);
    this.isShow = true;
  }

  hideMenu(): void {
    this.viewContainerRef.clear();
    this.isShow = false;
  }

  onRemove(event: any): void {
    this.clickRemove.emit();

    event.stopPropagation();
    this.hideMenu();
  }

  onFavorite(event: any): void {
    this.clickFavorite.emit();

    event.stopPropagation();
    this.hideMenu();
  }

  onMore(event: any): void {
    event.stopPropagation();
    console.log('on more');
    this.isShow ? this.hideMenu() : this.showMenu();
    console.log(this.isShow);
  }

  onRestore(event: any): void {
    this.clickRestore.emit();

    event.stopPropagation();
  }
}

<img
  *ngIf="!isArchived"
  [src]="(isDark$ | async) ? 'assets/svg/more_vert-dark-24px.svg' : 'assets/svg/more_vert-24px.svg'" alt="Date"
  (click)="onMore($event)">
<img
  *ngIf="isArchived"
  [src]="(isDark$ | async) ? 'assets/svg/restore_from_trash-dark-24px.svg' : 'assets/svg/restore_from_trash-24px.svg'"
  (click)="onRestore($event)">
<ng-container #container></ng-container>
<ng-template #template>
  <div class="more-menu" [ngClass]="{'dark': isDark$ | async}">
    <div class="more-menu__item" (click)="onFavorite($event)">
      <img *ngIf="!isFavorite; else favorite"
           [src]="(isDark$ | async) ? 'assets/svg/favorite_border-dark-24px.svg' : 'assets/svg/favorite_border-24px.svg'">
      <ng-template #favorite>
        <img [src]="(isDark$ | async) ? 'assets/svg/favorite-dark-24px.svg' : 'assets/svg/favorite-24px.svg'">
      </ng-template>
      <span>Add to Favourites</span>
    </div>
    <div class="more-menu__item" (click)="onRemove($event)">
      <img [src]="(isDark$ | async) ? 'assets/svg/delete-dark-24px.svg' : 'assets/svg/delete-24px.svg'">
      <span>Remove</span>
    </div>
  </div>
</ng-template>
