// react/src/ui/date-input/DateInput.tsx
import React, { useEffect, useState } from 'react'
import './DateInput.scss'

export const DateInput = () => {
  const [day, setDay] = useState()
  const [month, setMonth] = useState()
  const [year, setYear] = useState()
  const [error, setError] = useState<boolean>(false)

  // Validates that the input string is a valid date formatted as "mm/dd/yyyy"
  function isValidDate (dateString: string): boolean {
    // First check for the pattern
    if (!/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(dateString)) {
      return false
    }

    // Parse the date parts to integers
    const parts = dateString.split('/')
    const day = parseInt(parts[0], 10)
    const month = parseInt(parts[1], 10)
    const year = parseInt(parts[2], 10)

    // Check the ranges of month and year
    if (year < 1000 || year > 3000 || month === 0 || month > 12) {
      return false
    }

    const monthLength = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31]

    // Adjust for leap years
    if (year % 400 === 0 || (year % 100 !== 0 && year % 4 === 0)) {
      monthLength[1] = 29
    }

    // Check the range of the day
    return day > 0 && day <= monthLength[month - 1]
  }

  useEffect(() => {
    if (!isValidDate(`${day}/${month}/${year}`)) {
      setError(true)
    } else {
      setError(false)

      const date = new Date(
        year > 0 ? year - 1 : 0,
        month > 0 ? month - 1 : 0,
        day > 0 ? day - 1 : 0,
        0,
        0,
        0,
        0)

      console.log(date);
    }
  }, [day, month, year])

  return (
    <div className="date-input">
      <input placeholder="Day"
             type="number"
             value={day}
             onChange={e => setDay(e.target.value)}
             className={error ? 'error' : ''}/>
      <input placeholder="Month"
             type="number"
             value={month}
             onChange={e => setMonth(e.target.value)}
             className={error ? 'error' : ''}/>
      <input placeholder="Year"
             type="number"
             value={year}
             onChange={e => setYear(e.target.value)}
             className={error ? 'error' : ''}/>
    </div>
  )
}

// angular/src/app/ui/date-input/date-input.component.ts
import { Component, forwardRef, OnInit } from '@angular/core';
import { ControlValueAccessor, FormBuilder, FormGroup, NG_VALUE_ACCESSOR, Validators } from '@angular/forms';

@Component({
  selector: 'app-date-input',
  templateUrl: './date-input.component.html',
  styleUrls: ['./date-input.component.scss'],
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => DateInputComponent),
      multi: true,
    },
  ],
})
export class DateInputComponent implements ControlValueAccessor, OnInit {
  form: FormGroup = this.fb.group({
    day: ['', [Validators.required]],
    month: ['', [Validators.required]],
    year: ['', [Validators.required]]
  });

  constructor(private fb: FormBuilder) {}

  onChange: any = () => {};
  onTouch: any = () => {};

  set value(value) {
    this.onChange(value);
    this.onTouch(value);
  }

  writeValue(value: any): void {
    this.value = value;
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouch = fn;
  }

  // Validates that the input string is a valid date formatted as "mm/dd/yyyy"
  isValidDate(dateString): boolean {
    // First check for the pattern
    if (!/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(dateString)) {
      return false;
    }

    // Parse the date parts to integers
    const parts = dateString.split('/');
    const day = parseInt(parts[0], 10);
    const month = parseInt(parts[1], 10);
    const year = parseInt(parts[2], 10);

    // Check the ranges of month and year
    if (year < 1000 || year > 3000 || month === 0 || month > 12) {
      return false;
    }

    const monthLength = [ 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 ];

    // Adjust for leap years
    if (year % 400 === 0 || (year % 100 !== 0 && year % 4 === 0)) {
      monthLength[1] = 29;
    }

    // Check the range of the day
    return day > 0 && day <= monthLength[month - 1];
  }

  ngOnInit(): void {
    this.form.valueChanges.subscribe(value => {
      if (!this.isValidDate(`${this.form.controls.day.value}/${this.form.controls.month.value}/${this.form.controls.year.value}`)) {
        this.form.setErrors({ incorrect: true });
      } else {
        this.writeValue(
          new Date(
            this.form.controls.year.value > 0 ? this.form.controls.year.value - 1 : 0,
            this.form.controls.month.value > 0 ? this.form.controls.month.value - 1 : 0,
            this.form.controls.day.value > 0 ? this.form.controls.day.value - 1 : 0,
            0,
            0,
            0,
            0)
        );
      }
    });
  }
}

<div class="date-input" [formGroup]="form">
  <input placeholder="Day" formControlName="day" type="number">
  <input placeholder="Month" formControlName="month" type="number">
  <input placeholder="Year" formControlName="year" type="number">
</div>
