// react/src/features/new-card/NewCard.jsx
import React from 'react';
import './NewCard.scss';

export const NewCard = () => (
    <div className="wrapper">
        <div className="card">
            <div className="content">
                <div className="row">
                    <input type="text" placeholder="New..."/>
                    <div className="color-picker"></div>
                </div>
                <div className="row">
                    <div>Time widget</div>
                    <img src="%PUBLIC_URL%/assets/svg/access_time-24px.svg" alt="Favourite"/>
                </div>
            </div>
            <div className="card__bottom">
                <img src="%PUBLIC_URL%/assets/svg/clear-24px.svg" alt="Favourite"/>
                <img src="%PUBLIC_URL%/assets/svg/done-24px.svg" alt="Favourite"/>
            </div>
        </div>
    </div>

);

// angular/src/app/components/new-card/new-card.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-new-card',
  templateUrl: './new-card.component.html',
  styleUrls: ['./new-card.component.scss']
})
export class NewCardComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }
}

<div class="wrapper">
  <div class="card">
    <div class="content">
      <div class="row">
        <input type="text" placeholder="New...">
        <div class="color-picker"></div>
      </div>
      <div class="row">
        <div>Time widget</div>
        <img src="assets/svg/access_time-24px.svg" alt="Favourite">
      </div>
    </div>
    <div class="card__bottom">
      <img src="assets/svg/clear-24px.svg" alt="Favourite">
      <img src="assets/svg/done-24px.svg" alt="Favourite">
    </div>
  </div>
</div>
