// react/src/components/new-card/NewCard.tsx
import React from 'react'
import './NewCard.scss'
import { TaskCard } from '../../ui/task-card/TaskCard'
import { useHistory } from 'react-router-dom'
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service'
import { ITask } from '../../models/ITask'

export const NewCard = () => {
  const history = useHistory();
  const tasksStorageService = new TasksStorageService()

  function onAccept(task: ITask): void {
    tasksStorageService.addTask(task)
    history.push('/')
  }

  return (
    <div className="wrapper">
      <TaskCard
        accepted={onAccept}
        closed={() => history.push('/')}/>
    </div>
  )
}

// angular/src/app/components/new-card/new-card.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import { Router } from '@angular/router';
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service';
import { Task } from 'src/app/models/task';

@Component({
  selector: 'app-new-card',
  templateUrl: './new-card.component.html',
  styleUrls: ['./new-card.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush
})
export class NewCardComponent {

  constructor(
    private router: Router,
    private tasksStorage: TasksStorageService,
  ) { }

  onCancel(): void {
    this.router.navigate(['/']);
  }

  onDone(task: Task): void {
    this.tasksStorage.addTask(task as Task);
    this.router.navigate(['/']);
  }
}

<div class="wrapper">
  <app-task-card
    (closed)="onCancel()"
    (accepted)="onDone($event)"></app-task-card>
</div>
