// angular/src/app/ui/task-item/task-item.component.ts
import { ChangeDetectionStrategy, Component, Input } from '@angular/core';
import { Task } from 'src/app/models/task';
import { BehaviorSubject } from 'rxjs';
import { ThemeService } from '../../services/theme/theme.service';
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service';

@Component({
  selector: 'app-task-item',
  templateUrl: './task-item.component.html',
  styleUrls: ['./task-item.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TaskItemComponent {
  readonly isDark$: BehaviorSubject<boolean> = this.themeService.isDark$;

  @Input() task: Task;
  @Input() isActive: boolean;

  remaining: string;

  constructor(
    private themeService: ThemeService,
    private tasksStorage: TasksStorageService
  ) { }

  onFavorite(): void {
    this.task.isFavorite = !this.task.isFavorite;
    this.tasksStorage.updateTask(this.task);
  }

  onRemove(): void {
    this.task.isArchived = true;
    this.tasksStorage.updateTask(this.task);
  }

  onRestore(): void {
    this.task.isArchived = false;
    this.tasksStorage.updateTask(this.task);
  }

  /**
   * Calculates remaining time of task.
   */
  onTime(event: any): void {
    event.stopPropagation();
    this.isActive = true;
    this.remaining = `Remaining ${this.task.date}...`;
  }

  onBack(event: any): void {
    event.stopPropagation();
    this.isActive = false;
  }
}

<div class="item" [ngClass]="{'item--active': isActive}" [ngStyle]="{'border-color': color, 'background-color': isActive ? color : 'unset'}">
  <div class="text" [ngClass]="{'dark': isDark && !isActive}">{{title}}</div>
  <div class="buttons" *ngIf="!isActive; else activeButtons">
    <img *ngIf="!isFavorite; else favorite" [src]="isDark ? 'assets/svg/favorite_border-dark-24px.svg' : 'assets/svg/favorite_border-24px.svg'" (click)="onFavorite($event)">
    <ng-template #favorite>
      <img [src]="isDark ? 'assets/svg/favorite-dark-24px.svg' : 'assets/svg/favorite-24px.svg'" (click)="onFavorite($event)">
    </ng-template>
    <img [src]="isDark ? 'assets/svg/access_time-dark-24px.svg' : 'assets/svg/access_time-24px.svg'" (click)="onTime($event)">
  </div>
  <ng-template #activeButtons>
    <div class="buttons">
      <img src="assets/svg/east-24px.svg" (click)="onBack($event)">
    </div>
  </ng-template>
</div>

// react/src/ui/task-item/TaskItem.tsx
import React, { useContext, useState } from 'react'
import { useHistory } from 'react-router-dom'
import './TaskItem.scss'
import { MoreMenu } from '../more-menu/MoreMenu'
import { ReactComponent as AccessTimeIcon } from '../../assets/svg/access_time-24px.svg'
import { ReactComponent as AccessTimeDarkIcon } from '../../assets/svg/access_time-dark-24px.svg'
import { ReactComponent as EastIcon } from '../../assets/svg/east-24px.svg'
import { ITask } from '../../models/ITask'
import { ThemeContext } from '../../App'
import Themes from '../../models/themes'
import { TasksStorageService } from '../../services/tasks-storage/tasks-storage.service'

type TaskItemProps = {
  task: ITask;
  onClick?: () => void
}

export const TaskItem = ({ task, onClick }: TaskItemProps) => {
  const theme = useContext(ThemeContext)
  const history = useHistory()

  const [isActive, setIsActive] = useState(false)
  const [remaining, setRemaining] = useState('')

  const tasksStorage = new TasksStorageService()

  const onFavorite = () => {
    task.isFavorite = !task.isFavorite
    tasksStorage.updateTask(task)
  }

  const onRemove = () => {
    task.isArchived = true
    tasksStorage.updateTask(task)
  }

  const onRestore = () => {
    task.isArchived = false
    tasksStorage.updateTask(task)
  }

  const onTime = (event: any) => {
    event.stopPropagation()
    setIsActive(true)
    setRemaining(`Remaining ${task.date}...`)
  }

  const onBack = (event: any) => {
    event.stopPropagation()
    setIsActive(false)
  }

  return (
    <div
      className="item"
      style={{
        borderColor: task.color,
        backgroundColor: isActive ? task.color : 'unset',
      }}
      onClick={() => history.push({
        pathname: '/task',
        state: { task },
      })}>
      <div className={`text ${theme === Themes.DARK && !isActive
        ? 'dark'
        : null}`}>
        {isActive ? remaining : task?.title}
      </div>
      {
        isActive
          ?
          <div className="buttons">
            <EastIcon onClick={onBack}/>
          </div>
          :
          <div className="buttons">
            <MoreMenu
              isFavorite={task.isFavorite}
              isArchived={task.isArchived}
              onFavorite={onFavorite}
              onRemove={onRemove}
              onRestore={onRestore}/>
            {
              !task.isArchived ? theme === Themes.LIGHT
                ? <AccessTimeIcon onClick={onTime}/>
                : <AccessTimeDarkIcon onClick={onTime}/> : null
            }
          </div>
      }
    </div>
  )
}
